### ISSUE TITLE
Add result of AT%CONEVAL to roam.v.con

### ISSUE THREAD

**Issue by coderbyheart** [nRFCloud/thingyworld_fw#3]
Report the result of the `AT%CONEVAL` command as `roam.v.con` when reporting the roaming information, either as string, or as array; array is preferred cloud side, but whatever is easiest for the device.

String notation: `"0,0,8,59,21,35,\"032E9B05\",\"24201\",394,6400,20,0,0,-7,1,1,103"`

Array notation: `[0,0,8,59,21,35,"032E9B05","24201",394,6400,20,0,0,-7,1,1,103]`

**Comment by maxd-nordic** [comment]
Just synced with Simen - I'll add that myself.

**Comment by maxd-nordic** [comment]
support is added on my branch

**Comment by coderbyheart** [comment]
What's your branch?

**Comment by maxd-nordic** [comment]
https://github.com/maxd-nordic/sdk-nrf/tree/atv2-ina3221
